---
apiVersion: v1
kind: Pod
metadata:
  name: grpc-client
  labels:
    app: grpc-client
spec:
  containers:
  - name: client
    image: quay.io/jvdm/stackrox-dev:go-grpc-lb-poc-client
    imagePullPolicy: Always
    env:
    - name: SERVER_HOSTNAME
      value: "grpc-server"
    - name: GRPC_GO_LOG_SEVERITY_LEVEL
      value: "info"
    ports:
    - name: metrics
      containerPort: 8081
